# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAppDelegate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAppDelegate
  
#  ENV["ThinkingSDK_source"] = '1'
#  pod 'ThinkingSDK', :path => '../../../td_yazhou/ios-sdk'
  pod 'ThinkingSDK', '2.8.1.7'
  pod 'TPNS-iOS', '1.3.9.1'
  
end
